# Generated by Django 2.1 on 2018-09-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='waiter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
