# Generated by Django 2.1 on 2018-09-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180906_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventoryout',
            name='issued_to',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='issued_to',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
