# Generated by Django 2.1 on 2018-09-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180906_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventoryout',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
    ]
