# Generated by Django 2.1 on 2018-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180906_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventoryout',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
