# Generated by Django 2.1 on 2018-09-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180906_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeexpense',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ExpenseCategory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InventoryCategory'),
        ),
        migrations.AlterField(
            model_name='inventoryin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InventoryCategory'),
        ),
        migrations.AlterField(
            model_name='inventoryout',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.InventoryCategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='mostsellingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Table'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Item'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Order'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Inventory'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Item'),
        ),
    ]
